- name: grab facts for Check Point CloudGuard Security Management (SECURITY MODE)
  ec2_instance_facts:
    region: "{{ ec2_region }}"
    filters:
      instance-state-name: running
      "tag:Workshop_security": "{{ec2_name_prefix}}-security"
  register: secruity_node_facts

- name: ADD Check Point CloudGuard Security Management TO INVENTORY
  add_host:
    name: "{{ item.tags.Name }}"
    short_name: "{{ item.tags.short_name }}"
    ansible_host: "{{ item.public_ip_address }}"
    username: "{{ item.tags.Student }}"
    ansible_user: "{{ item.tags.username }}"
    ansible_port: "{{ ssh_port }}"
    ansible_ssh_private_key_file: "{{ playbook_dir }}/{{ec2_name_prefix}}/{{ec2_name_prefix}}-private.pem"
    private_ip: "{{item.private_ip_address}}"
    ansible_network_os: "{{item.tags.ansible_network_os}}"
    groups:
      - core
      - security
  loop: "{{ security_node_facts.instances|flatten(levels=1) }}"

- name: Generate student inventories
  template:
    src: networking_instances.txt.j2
    dest: "{{ playbook_dir }}/{{ec2_name_prefix}}/student{{item}}-instances.txt"
  with_sequence: count="{{ student_total }}"

- name: Generate student etchosts
  template:
    src: etchosts_networking.j2
    dest: "{{ playbook_dir }}/{{ec2_name_prefix}}/student{{item}}-etchosts.txt"
  with_sequence: count="{{ student_total }}"

- name: Generate instructor inventory
  template:
    src: instructor_inventory_networking.j2
    dest: "{{ playbook_dir }}/{{ec2_name_prefix}}/instructor_inventory.txt"
