#### CHECK POINT AMI
- name: BLOCK FOR CHECK POINT AMI
  block:
  - name: find ami for check point (SECURITY MODE)
    ec2_ami_facts:
      region: "{{ ec2_region }}"
      owners: "679593333241"
      filters:
        name: "Check Point CloudGuard IaaS*PAYG-MGMT*R80.20*"
        architecture: "x86_64"
    register: checkpoint_ami_list

  - name: save ami for check point (SECURITY MODE)
    set_fact:
      checkpoint_ami: >
        {{ checkpoint_ami_list.images | selectattr('name', 'defined') | sort(attribute='creation_date') | last }}
